name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  ci:
    permissions:
      contents: read
    uses: The-Running-Dev/GitHub-ActionTemplates/.github/workflows/pwsh-ci.yml@v0
    with:
      os: '["ubuntu-latest", "windows-latest"]'
      analyzer: true
      analyzer-settings: PSScriptAnalyzerSettings.psd1
      coverage: src
      minimum-coverage: '80'
