import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One sidebar generated from the docs/ folder structure. Order pages with `sidebar_position`
// front matter or `_category_.json` files.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
